### ISSUE TITLE
Allow setting and testing memory in config files

### ISSUE THREAD

**Issue by ISSOtm** [eievui5/evunit#11]
What is says on the tin. Suggested syntax: `[8:addr]`, `[16l:addr]`, `[16b:addr]` (specifying endianness). Larger sizes can be checked by composing, 16-bit is a convenience that cuts in half other "decompositions". (Endianness is too annoying to specify past 16-bit, too.)

**Comment by Rangi42** [comment]
TOML allows quoted key names, so I'd just suggest `"[Label]" = value`. For example:

```toml
[IsShiny]
pc = "CheckShininess"
hl = "wTempMonDVs"
"[wTempMonDVs]" = 0xEA
"[wTempMonDVs+1]" = 0xAA
[IsShiny.result]
f.c = 1

[IsNotShiny]
pc = "CheckShininess"
hl = "wTempMonDVs"
"[wTempMonDVs]" = 0xFF
"[wTempMonDVs+1]" = 0xFF
[IsNotShiny.result]
f.c = 0
```
