### ISSUE TITLE
Dump does not actually show memory content

### ISSUE THREAD

**Issue by elialm** [eievui5/evunit#32]
I was busy testing a function, but upon checking the dumps I could not see the expected values in memory. As an example, I was running this test:

```toml
[sd_calculate_crc7-0]
pc = "sd_calculate_crc7"
hl = "xram_errors"
b = 5
"[xram_errors]" = [ 0x40, 0x00, 0x00, 0x00, 0x00 ]
[sd_calculate_crc7-0.result]
a = 0b10010100
```

Here I set some values at `xram_errors`, which is at `$C000` (if the `.sym` file is to be believed). However, upon checking the associated dump of the test, I see the following:

```
[WRAM 0]
0xc000: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
0xc010: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
0xc020: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
0xc030: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
0xc040: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
0xc050: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
...
```

The values I set at `xram_errors` are not shown here, but the test still passes as if these values are here. I am guessing there is a bug in the dump file generation, which should be an easy fix. I plan to look at it tomorrow (Sunday CET).
